name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-jar
        path: ../*
        retention-days: 7
